apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: orders-project-staging-customer-service
spec:
  hosts:
  - "customer-service.orders-project-staging.jahn.demo.keptn.sh"
  gateways:
  - orders-project-staging-gateway
  http:
    - route:
      - destination:
          host: customer-service.orders-project-staging.svc.cluster.local
          subset: blue
        weight: 0
      - destination:
          host: customer-service.orders-project-staging.svc.cluster.local
          subset: green
        weight: 100